name: 问题反馈 🐛 (Bug Report)
description: 提交一份报告，帮助我们改进项目
labels: ["(S1 - Need confirmation)"]

body:
  - type: markdown
    attributes:
      value: |
        请花点时间填写下面所有字段。

  - type: textarea
    id: description-of-bug
    attributes:
      label: 描述这个 bug
      description: 清晰、简洁地描述这个 bug 是什么。
      placeholder: 瞄准等级无法提升。
    validations:
      required: true

  - type: textarea
    id: save-file
    attributes:
      label: 附上存档文件
      description: |
        `ESC` 主菜单 -> `d` 导出用于 github 问题反馈的存档压缩包
      placeholder: |
        如不适用请填写 N/A。

        - 如果没有存档文件，这个问题反馈很可能无法被解决，除非它极易复现或复现步骤十分完整。
        - 最好把存档准备成「加载后即可立即按复现步骤操作」的状态，这样尝试复现的人就不必先做无关的手动操作（比如先走到某个地方）。
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 复现步骤
      description: |
        复现该现象的步骤。
        **检查你的 Mod！** 请务必测试到底是哪个 Mod（如果有的话）真正导致了这个问题。
        参与其中的无关 Mod 越少，就越容易复现和确认问题。
      placeholder: |
        1. 创建一个带枪、弹匣和一些弹药的角色。
        2. 试着瞄准一面墙。
        3. 没有任何办法提升瞄准等级。
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望的行为
      description: |
        清晰、简洁地描述你期望发生的情况。
        最好也说明一下你为什么期望它这样。
      placeholder: 我期望瞄准等级能够提升，因为其他所有技能都能升级。
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: |
        **如适用**，请附上截图来帮助说明你的问题。
        不要只截崩溃窗口的图。如果发生崩溃，请在「补充说明」中提供崩溃日志。
    validations:
      required: false

  - type: textarea
    id: versions-and-config
    attributes:
      label: 版本与配置信息
      description: |
        `ESC` 主菜单 -> `d` 导出用于 github 问题反馈的存档压缩包 -> 按屏幕提示操作
      placeholder: |
        - 操作系统: [例如 iOS 8 或 Windows 10 或 Ubuntu 18.04]
        - 游戏版本: [例如 d6ec466 (64-bit)]
        - 图形版本: [Tiles 图块版 或 Terminal 终端版]
        - 游戏内语言: [例如 简体中文 / 繁体中文 / 英文 等]
        - 已加载的 Mod: [例如 dda, boats, hacktheplanet, StatsThroughSkills]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 补充说明
      description: 在此添加关于该问题的其他背景信息。
      placeholder: |
        崩溃：如果你的问题涉及崩溃，请把以下文件添加到「补充说明」段落：
          - 来自 /config 文件夹（可以把两个文件一起打包成 zip）：
            - crash.log 文件。
            - debug.log 文件。
          - 你的存档文件（打包成 zip）

        - 提示 #1：你可以直接把文件拖拽到这个 issue 帖子里！
        - 提示 #2：在发生崩溃时，提供存档文件对我们非常重要。它能极大帮助开发者复现并修复 bug。
        如果可以，请尽量提供一个处于正确条件下、崩溃发生前的存档。
    validations:
      required: false